### ISSUE TITLE
Issue about the process of  LASCO C2 data

### ISSUE THREAD

**Issue by Rui-Zhuo** [Helioviewer-Project/fits2img#2]
Hi bogdanni,
    My name is Rui Zhuo, a doctoral student from Peking University, in Prof. Jiansen He's group. We are now working on the flapping motion of heliospheric current sheet, and hope to decect it through the remote-sensing images of coronal streamers by LASCO C2. 
    LASCO Level-0.5 data is raw photon counts and thus inconvenient to deal with for us. We have asked the LASCO team about the fully calibrated Level-1 data in January 2021, but they could only provide Level-1 before 2017. And we notice that Helioviewer provides jp2 data which is clearer than Level-0.5 and good for qualitative studies. We read 'fits2img.c', which includes the noise reducing, sharpness enhance, gamma and log transform etc., and are now writing to you for some questions about the process of LASCO C2 data on Helioviewer. Our questions are about,
    1) How exactly does the code remove F-corona and other stray lights?
    2) Which Level is the input fits data of LASCO C2? If it is based on Level-0.5, are there any proporocess for it?
    3) How can we get the data which is as good as those images shown in Helioviewer's website, and can be further processed (to be specific, multi-scale gaussian normalization)?
    We are very thankful for your help, and looking for your reply!
                                                                                                                                          Best wishes,
                                                                                                                                          Rui Zhuo

**Comment by bogdanni** [comment]
Hi, the LASCO JP2 files are produced by another program: https://github.com/Helioviewer-Project/jp2gen
Here is the probably what are you looking for: https://github.com/Helioviewer-Project/jp2gen/tree/master/idl/soho/lasco

**Comment by Rui-Zhuo** [comment]
OK I find it. Thank you so much!
